# Generated by Django 5.0.2 on 2024-03-06 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_itemordered_paid_time_itemordered_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemordered',
            name='item_color',
            field=models.CharField(blank=True, max_length=33, null=True),
        ),
        migrations.AddField(
            model_name='itemordered',
            name='item_size',
            field=models.CharField(blank=True, max_length=33, null=True),
        ),
    ]
