# Generated by Django 5.0.2 on 2024-02-17 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useraddress',
            old_name='mobile',
            new_name='address_mobile',
        ),
    ]
