# Generated by Django 5.0.2 on 2024-02-21 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Colores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=22)),
            ],
        ),
        migrations.CreateModel(
            name='Sizes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=22)),
            ],
        ),
        migrations.CreateModel(
            name='Tshirt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=33)),
                ('item_info', models.CharField(max_length=99)),
                ('item_price', models.PositiveIntegerField()),
                ('added_time', models.DateTimeField(auto_now_add=True)),
                ('main_image', models.ImageField(upload_to='img/%y%m%d%H%M')),
                ('image_white', models.ImageField(blank=True, null=True, upload_to='img/%y%m%d%H%M')),
                ('image_orange', models.ImageField(blank=True, null=True, upload_to='img/%y%m%d%H%M')),
                ('image_pink', models.ImageField(blank=True, null=True, upload_to='img/%y%m%d%H%M')),
                ('image_purple', models.ImageField(blank=True, null=True, upload_to='img/%y%m%d%H%M')),
                ('image_blue', models.ImageField(blank=True, null=True, upload_to='img/%y%m%d%H%M')),
                ('image_red', models.ImageField(blank=True, null=True, upload_to='img/%y%m%d%H%M')),
                ('image_black', models.ImageField(blank=True, null=True, upload_to='img/%y%m%d%H%M')),
                ('image_green', models.ImageField(blank=True, null=True, upload_to='img/%y%m%d%H%M')),
                ('available_colores', models.ManyToManyField(to='shop.colores')),
                ('available_sizes', models.ManyToManyField(to='shop.sizes')),
            ],
        ),
    ]
