# Generated by Django 5.0.2 on 2024-02-22 19:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AllClothes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=33)),
                ('item_info', models.TextField()),
                ('item_price', models.PositiveIntegerField()),
                ('added_time', models.DateTimeField(auto_now_add=True)),
                ('main_image', models.ImageField(upload_to='img/%y%m%d%H%M')),
                ('image_white', models.ImageField(blank=True, null=True, upload_to='img/%y%m%d%H%M')),
                ('image_orange', models.ImageField(blank=True, null=True, upload_to='img/%y%m%d%H%M')),
                ('image_pink', models.ImageField(blank=True, null=True, upload_to='img/%y%m%d%H%M')),
                ('image_purple', models.ImageField(blank=True, null=True, upload_to='img/%y%m%d%H%M')),
                ('image_blue', models.ImageField(blank=True, null=True, upload_to='img/%y%m%d%H%M')),
                ('image_red', models.ImageField(blank=True, null=True, upload_to='img/%y%m%d%H%M')),
                ('image_black', models.ImageField(blank=True, null=True, upload_to='img/%y%m%d%H%M')),
                ('image_green', models.ImageField(blank=True, null=True, upload_to='img/%y%m%d%H%M')),
            ],
        ),
        migrations.CreateModel(
            name='ClothesCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=33)),
            ],
        ),
        migrations.CreateModel(
            name='Colores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=22)),
            ],
        ),
        migrations.CreateModel(
            name='Sizes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=22)),
            ],
        ),
        migrations.CreateModel(
            name='AddCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_color', models.CharField(max_length=22)),
                ('selected_size', models.CharField(max_length=22)),
                ('selected_quantity', models.CharField(max_length=4)),
                ('total_price', models.CharField(max_length=9)),
                ('order_time', models.DateTimeField(auto_now_add=True)),
                ('is_paid', models.BooleanField(default=False)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addCart_customer', to=settings.AUTH_USER_MODEL)),
                ('selected_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addCart_selectedProduct', to='shop.allclothes')),
            ],
        ),
        migrations.AddField(
            model_name='allclothes',
            name='item_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allClothes_itemCategory', to='shop.clothescategory'),
        ),
        migrations.AddField(
            model_name='allclothes',
            name='available_colores',
            field=models.ManyToManyField(to='shop.colores'),
        ),
        migrations.AddField(
            model_name='allclothes',
            name='available_sizes',
            field=models.ManyToManyField(to='shop.sizes'),
        ),
    ]
