# Generated by Django 5.0.2 on 2024-02-23 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_addcart_guest_session_id_alter_addcart_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addcart',
            name='guest_session_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
