# Generated by Django 5.0.2 on 2024-03-02 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_addcart_guest_session_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='allclothes',
            name='discount',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='allclothes',
            name='discount_percentage',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='allclothes',
            name='item_price_on_discount',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
