# Generated by Django 5.0.2 on 2024-03-25 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_alter_allclothes_discount_percentage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addcart',
            name='total_price',
            field=models.CharField(max_length=22),
        ),
    ]
